### ISSUE TITLE
Error: $ operator is invalid for atomic vectors

### ISSUE THREAD

**Issue by fed1942** [DOI-USGS/EflowStats#193]
Hi all, i am unable to use any of the functions (cal_durationhigh, calc_allHIT, etc.) of the Eflowstats package. I always get the same error:
Error: $ operator is invalid for atomic vectors

Using any of the .txt files that circulate on the forum (#161), the error stops appearing. However, despite copying the format of these files, I am unable to produce a working .txt file of my own.

Any ideas? I attach the file.

[Test.txt](https://github.com/DOI-USGS/EflowStats/files/11212647/Test.txt)

Thank you in advance.

**Comment by dblodgett-usgs** [comment]
Can you please submit a reprex so I can tell what you are trying to do with the text file? 

https://community.rstudio.com/t/faq-whats-a-reproducible-example-reprex-and-how-do-i-create-one/5219 will help explain how to put one together.

**Comment by fed1942** [comment]
I am using EflowStats v5.00, but i have the same problem with the latest version (5.03).

### This is my code:

library(EflowStats)

Tabla = read.delim("C:/Users/fhaspert/Desktop/Test.txt", header=TRUE, sep="\t")
Tabla[,1] = as.Date(Tabla[,1])
Tabla[,2] = as.numeric(Tabla[,2])
yearType = "water"
calc_durationHigh(x = Tabla, yearType = yearType)

### This is the error:

Error: $ operator is invalid for atomic vectors
Además: Warning message:
In validate_data(x, yearType) :
  Every year as defined by the yearType argument must be complete, 
                    the following years have missing data: 1956,1957,1958,1963,1976,1977,1992,2009,2017,2018,2019,2020,2021,2022

Recently i found that if i remove the years with missing data and change yeartype to "calendar", the error stops appearing (Test_2.txt).

[Test.txt](https://github.com/DOI-USGS/EflowStats/files/11233100/Test.txt)

[Test_2.txt](https://github.com/DOI-USGS/EflowStats/files/11233160/Test_2.txt)

**Comment by dblodgett-usgs** [comment]
The message that is being emitted is the issue. 

```
Every year as defined by the yearType argument must be complete,
the following years have missing data: 1956,1957,1958,1963,1976,1977,1992,2009,2017,2018,2019,2020,2021,2022
```

**Comment by fed1942** [comment]
I thought there were two different errors. 

Thank you.

**Comment by dblodgett-usgs** [comment]
I've put in some changes that will make the erroneous error go away. 

`remotes::install_github("doi-usgs/EflowStats@v5.1.1")` will get you the latest version.
